"""
healthcare_guidelines.py
-------------------------
AgentForge — Healthcare RCM AI Agent — Hardcoded compliance constants
----------------------------------------------------------------------
Module-level constants only. No functions. Contains FDA rules, HIPAA
PII fields, ICD-10 validation patterns, clinical safety thresholds,
and severity level definitions. Used by verification.py.

Author: Shreelakshmi Gopinatha Rao
Project: AgentForge — Healthcare RCM AI Agent
"""

# Drug interaction severity levels (FDA Drug Safety Guidelines)
SEVERITY_LEVELS = ["CONTRAINDICATED", "HIGH", "MEDIUM", "LOW"]

# Severities that ALWAYS require physician review — never auto-approve
FDA_SEVERITIES_REQUIRING_PHYSICIAN_REVIEW = ["HIGH", "CONTRAINDICATED"]

# Severity that can auto-approve with monitoring note
FDA_AUTO_APPROVE_SEVERITY = "LOW"

# FDA rules for interaction handling
FDA_RULES = {
    "physician_review_required": FDA_SEVERITIES_REQUIRING_PHYSICIAN_REVIEW,
    "auto_approve_with_monitoring": FDA_AUTO_APPROVE_SEVERITY,
    "source": "FDA Drug Safety Guidelines",
}

# HIPAA — fields that must NEVER appear in logs
HIPAA_RULES = {
    "pii_fields": ["name", "ssn", "dob", "address", "phone", "email", "mrn"],
    "retention_requirements": "Follow organizational policy",
}

# ICD-10-CM code format validation (basic pattern: letter + digits)
ICD10_RULES = {
    "validation_pattern": r"^[A-Z]\d{2}(\.\d{2,4})?$",
}

# Drug class / family map — used to catch cross-class allergy conflicts.
# Key: allergy name (lowercase). Value: list of drug names in that class (lowercase).
# Example: a patient allergic to "penicillin" should also be flagged for amoxicillin,
# ampicillin, etc., because they share the beta-lactam core structure.
DRUG_CLASS_ALLERGY_MAP: dict = {
    "penicillin": [
        "amoxicillin", "ampicillin", "oxacillin", "dicloxacillin",
        "nafcillin", "piperacillin", "ticarcillin", "amoxicillin-clavulanate",
        "ampicillin-sulbactam", "piperacillin-tazobactam",
    ],
    "sulfa": [
        "sulfamethoxazole", "trimethoprim-sulfamethoxazole", "bactrim",
        "septra", "sulfadiazine", "sulfasalazine",
    ],
    "cephalosporin": [
        "cephalexin", "cefazolin", "cefdinir", "ceftriaxone", "cefuroxime",
        "cefepime", "ceftazidime", "cefpodoxime",
    ],
    "nsaid": [
        "ibuprofen", "naproxen", "aspirin", "celecoxib", "indomethacin",
        "ketorolac", "diclofenac", "meloxicam", "piroxicam",
    ],
    "latex": [],
}

# Clinical safety thresholds and rules
CLINICAL_SAFETY_RULES = {
    "confidence_threshold": 0.90,
    "allergy_conflict_deduction": 0.20,
    "interaction_found_deduction": 0.10,
    "max_review_loop_iterations": 3,
    "disclaimer": (
        "This information is generated by an AI assistant and is intended to support — "
        "not replace — clinical judgment. Always consult a qualified healthcare "
        "professional before making medical decisions."
    ),
}
